# Generated by Django 3.0.5 on 2020-05-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200506_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/'),
        ),
    ]
