# Generated by Django 3.0.8 on 2020-07-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=10000, max_digits=8, null=True),
        ),
    ]
