# Generated by Django 3.0.6 on 2020-05-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hashtags',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='HashTags',
        ),
    ]
